
/*
 * 
 */

package webservice.net.ilkj.soap.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.1.2
 * Sat Jul 19 19:55:44 CST 2014
 * Generated source version: 2.1.2
 * 
 */


@WebServiceClient(name = "HelloServiceImplService", 
                  wsdlLocation = "http://127.0.0.1:8080/webServices/helloService?wsdl",
                  targetNamespace = "http://client.soap.ilkj.net.webservice") 
public class HelloServiceImplService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://client.soap.ilkj.net.webservice", "HelloServiceImplService");
    public final static QName HelloServiceImplPort = new QName("http://client.soap.ilkj.net.webservice", "HelloServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:8080/webServices/helloService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://127.0.0.1:8080/webServices/helloService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public HelloServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HelloServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns IHelloService
     */
    @WebEndpoint(name = "HelloServiceImplPort")
    public IHelloService getHelloServiceImplPort() {
        return super.getPort(HelloServiceImplPort, IHelloService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IHelloService
     */
    @WebEndpoint(name = "HelloServiceImplPort")
    public IHelloService getHelloServiceImplPort(WebServiceFeature... features) {
        return super.getPort(HelloServiceImplPort, IHelloService.class, features);
    }

}
