package webservice.net.ilkj.soap.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.1.2
 * Sat Jul 19 19:55:43 CST 2014
 * Generated source version: 2.1.2
 * 
 */
 
@WebService(targetNamespace = "http://client.soap.ilkj.net.webservice", name = "IHelloService")
@XmlSeeAlso({ObjectFactory.class})
public interface IHelloService {

    @RequestWrapper(localName = "testWebServiceContext", targetNamespace = "http://client.soap.ilkj.net.webservice", className = "webservice.net.ilkj.soap.client.TestWebServiceContext")
    @ResponseWrapper(localName = "testWebServiceContextResponse", targetNamespace = "http://client.soap.ilkj.net.webservice", className = "webservice.net.ilkj.soap.client.TestWebServiceContextResponse")
    @WebMethod
    public void testWebServiceContext();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "selectMaxAgeStudent", targetNamespace = "http://client.soap.ilkj.net.webservice", className = "webservice.net.ilkj.soap.client.SelectMaxAgeStudent")
    @ResponseWrapper(localName = "selectMaxAgeStudentResponse", targetNamespace = "http://client.soap.ilkj.net.webservice", className = "webservice.net.ilkj.soap.client.SelectMaxAgeStudentResponse")
    @WebMethod
    public Customer selectMaxAgeStudent(
            @WebParam( name = "c1", targetNamespace = "" )
            Customer c1,
            @WebParam( name = "c2", targetNamespace = "" )
            Customer c2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getCustomerWithAttachment", targetNamespace = "http://client.soap.ilkj.net.webservice", className = "webservice.net.ilkj.soap.client.GetCustomerWithAttachment")
    @ResponseWrapper(localName = "getCustomerWithAttachmentResponse", targetNamespace = "http://client.soap.ilkj.net.webservice", className = "webservice.net.ilkj.soap.client.GetCustomerWithAttachmentResponse")
    @WebMethod
    public Customer getCustomerWithAttachment();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "selectMaxLongNameStudent", targetNamespace = "http://client.soap.ilkj.net.webservice", className = "webservice.net.ilkj.soap.client.SelectMaxLongNameStudent")
    @ResponseWrapper(localName = "selectMaxLongNameStudentResponse", targetNamespace = "http://client.soap.ilkj.net.webservice", className = "webservice.net.ilkj.soap.client.SelectMaxLongNameStudentResponse")
    @WebMethod
    public Customer selectMaxLongNameStudent(
            @WebParam( name = "c1", targetNamespace = "" )
            Customer c1,
            @WebParam( name = "c2", targetNamespace = "" )
            Customer c2
    );
}
